module.exports = {
	apps: [
		{
			name: 'Ma-Governance',
			script: './dist/index.js',
			watch: true,
			autorestart: true,
			instances: 1,
			exec_mode: 'cluster',
			env: {
				NODE_ENV: 'development',
				PORT: '3001',
				HOST: 'localhost',
				TIMEZONE: 'America/Sao_Paulo',
				DB_CLIENT: 'mysql',
				DB_HOST: '127.0.0.1',
				DB_NAME: 'magovernance',
				DB_USER: 'root',
				DB_PASSWORD: 'root@100',
				DB_PORT: '3306',
				DB_MIGRATION_DIRECTORY: './database/migrations',
				DB_MIGRATION_EXTENSION: 'ts',
				DB_POOL_MIN: '2',
				DB_POOL_MAX: '20',
				DB_USE_NULL_DEFAULT: 'true',
				CORS_ORIGIN: '*',
				CORS_METHODS: 'GET,HEAD,PUT,PATCH,POST,DELETE',
				CORS_PREFLIGHT_CONTIME: 'fale',
				CORS_OPTIONS_SUCCESS_STATUS: '200',
				ENABLE_CACHE: 'false',
				CACHE_TIME: '5',
				REDIS_HOST: 'localhost',
				REDIS_PORT: '6379',
				STORAGE_TYPE: 'local',
				AWS_ACCESS_KEY_ID: 'AKIA3S2IG3HVNSW7LCXC',
				AWS_SECRET_ACCESS_KEY: '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',
				AWS_REGION: 'sa-east-1',
				AWS_BUCKET: 'upload-ex',
				ENABLE_HTTPS: 'true',
				HTTPS_CERT_FILE: './certs/cert.pem',
				HTTPS_KEY_FILE: './certs/key.pem',
				SALT_ROUNDS: '14',
				AUTHSECRET: '@testeAPI11',
				MAILER_HOST: '',
				MAILER_PORT: '',
				MAILER_SERVICE: 'gmail',
				MAILER_USER: 'rta.home.306@gmail.com',
				MAILER_PASSWORD: 'xldiebqghhfsaqtz',
				EMAIL_DEFAULT: 'rta.home.306@gmail.com',
				MAIL_TO_REDIRECT: 'www.logan.resident@gmail.com',
			},
		},
	],
};
