import { Knex } from 'knex';
import { PropositionsType } from 'src/repositories/entities';
import { IPropositionsTypeViewModel } from 'src/repositories/types';
import { convertDataValues } from 'src/utils';

const data: IPropositionsTypeViewModel[] = [
	{
		name: 'Comunicados',
		fileId: 1,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{ name: 'Termo de Colaboração', description: undefined, active: true, subTypes: [], fileId: 2 },
	{ name: 'Acordo de Cooperação Eventos', description: undefined, active: true, subTypes: [], fileId: 3 },
	{ name: 'Acordo de Cooperação Compartilhamento de Bens', description: undefined, active: true, subTypes: [], fileId: 4 },
	{ name: 'Lista de Verificação(Sem Compartilhamento Patrimônio)', description: undefined, active: true, subTypes: [], fileId: 5 },
	{ name: 'Lista de Verificação(Termo de Colaboração)', description: undefined, active: true, subTypes: [], fileId: 6 },
	{ name: 'Edital Colaboração', description: undefined, active: true, subTypes: [], fileId: 7 },
	{ name: 'Edital Fomento', description: undefined, active: true, subTypes: [], fileId: 8 },
	{ name: 'Acordo de Cooperação Técnica', description: undefined, active: true, subTypes: [], fileId: 9 },
	{ name: 'Minuta de Repasse', description: undefined, active: true, subTypes: [], fileId: 10 },
	{ name: 'Plano de Trabalho Protocolo de Intenções(Sem Repasse)', description: undefined, active: true, subTypes: [], fileId: 11 },
	{ name: 'Plano de Trabalho Cooperação Técnica(Sem Repasse)', description: undefined, active: true, subTypes: [], fileId: 12 },
	{ name: 'Protocolo de Intenções', description: undefined, active: true, subTypes: [], fileId: 13 },
	{ name: 'Declaração de Regularidade Pagamentos Precatórios', description: undefined, active: true, subTypes: [], fileId: 14 },
	{ name: 'Lista de Verificação Entes Públicos', description: undefined, active: true, subTypes: [], fileId: 15 },
	{ name: 'Minuta Obras', description: undefined, active: true, subTypes: [], fileId: 16 },
	{ name: 'Edital de Chamamento Público', description: undefined, active: true, subTypes: [], fileId: 17 },
	{ name: 'Termo(Sem execução de Serviços de Engenharia)', description: undefined, active: true, subTypes: [], fileId: 18 },
	{
		name: 'Termos de Execução Descentralizada',
		description: undefined,
		fileId: 19,
		active: true,
		subTypes: [],
	},
	{ name: 'Decreto Legislativo', description: undefined, active: true, subTypes: [], fileId: 20 },
	{ name: 'Data Comemorativa', description: undefined, active: true, subTypes: [], fileId: 21 },
	{ name: 'Declaração de Utilidade Pública', description: undefined, active: true, subTypes: [], fileId: 22 },
	{ name: 'Lei Complementar', description: undefined, active: true, subTypes: [], fileId: 23 },
	{ name: 'Lei Ordinária', description: undefined, active: true, subTypes: [], fileId: 24 },
	{ name: 'Denominação de Local', description: undefined, active: true, subTypes: [], fileId: 25 },
	{ name: 'Doação de Imóveis', description: undefined, active: true, subTypes: [], fileId: 26 },
	{ name: 'Resolução', description: undefined, active: true, subTypes: [], fileId: 27 },
	{ name: 'Emendas Parlamentares Gerais', description: undefined, active: true, subTypes: [], fileId: 28 },
	{ name: 'Emenda de Lei Orgânica', description: undefined, active: true, subTypes: [], fileId: 29 },
	{ name: 'Emenda Orçamentária', description: undefined, active: true, subTypes: [], fileId: 30 },
	{ name: 'PEC', description: undefined, active: true, subTypes: [], fileId: 31 },
	{ name: 'Ação', description: undefined, active: true, subTypes: [], fileId: 32 },
	{ name: 'Solicitação de Informação', description: undefined, active: true, subTypes: [], fileId: 33 },
	{ name: 'Utilidade Pública', description: undefined, active: true, subTypes: [], fileId: 34 },
	{ name: 'Registro de Preço', description: undefined, active: true, subTypes: [], fileId: 35 },
	{ name: 'Serviços Comuns de Engenharia', description: undefined, active: true, subTypes: [], fileId: 36 },
	{ name: 'Serviços Continuados Exclusivos', description: undefined, active: true, subTypes: [], fileId: 37 },
	{ name: 'Serviços Continuados Não Exclusivos', description: undefined, active: true, subTypes: [], fileId: 38 },
	{ name: 'Serviços Não Continuados', description: undefined, active: true, subTypes: [], fileId: 39 },
	{ name: 'Serviços de Tecnologia - TIC', description: undefined, active: true, subTypes: [], fileId: 40 },
	{ name: 'Compras', description: undefined, active: true, subTypes: [], fileId: 41 },
	{ name: 'Serviços de Engenharia', description: undefined, active: true, subTypes: [], fileId: 42 },
	{ name: 'Serviços Comuns de Engenharia', description: undefined, active: true, subTypes: [], fileId: 43 },
	{ name: 'Projeto Básico de Engenharia', description: undefined, active: true, subTypes: [], fileId: 44 },
	{ name: 'Serviços Continuados Exclusivos', description: undefined, active: true, subTypes: [], fileId: 45 },
	{ name: 'Serviços Continuados Não Exclusivos', description: undefined, active: true, subTypes: [], fileId: 46 },
	{ name: 'Serviços de Tecnologia - TIC', description: undefined, active: true, subTypes: [], fileId: 47 },
	{ name: 'Serviços Não Continuados', description: undefined, active: true, subTypes: [], fileId: 48 },
	{ name: 'Capacitação de Inexigibilidade Licitação', description: undefined, active: true, subTypes: [], fileId: 49 },
	{ name: 'Projeto Básico de Inexigibilidade', description: undefined, active: true, subTypes: [], fileId: 50 },
	{ name: 'Minuta de Dispensa Eletrônica', description: undefined, active: true, subTypes: [], fileId: 51 },
	{ name: 'Termo de Justificativa de Técnica Relevante', description: undefined, active: true, subTypes: [], fileId: 52 },
	{ name: 'Termo de Locação de Imóvel', description: undefined, active: true, subTypes: [], fileId: 53 },
	{ name: 'Coleta Seletiva', description: undefined, active: true, subTypes: [], fileId: 54 },
	{ name: 'Processo Licitatório Presencial', description: undefined, active: true, subTypes: [], fileId: 55 },
	{ name: 'Pregão Compras', description: undefined, active: true, subTypes: [], fileId: 56 },
	{ name: 'Pregão Engenharia', description: undefined, active: true, subTypes: [], fileId: 57 },
	{ name: 'Pregão Eletrônico Sem Exclusividade', description: undefined, active: true, subTypes: [], fileId: 58 },
	{ name: 'Serviços Continuados Não Exclusivos', description: undefined, active: true, subTypes: [], fileId: 59 },
	{ name: 'Serviços Não Continuados', description: undefined, active: true, subTypes: [], fileId: 60 },
	{ name: 'Serviços de Dedicação Exclusiva', description: undefined, active: true, subTypes: [], fileId: 61 },
	{ name: 'Serviços de Tecnologia - TIC', description: undefined, active: true, subTypes: [], fileId: 62 },
	{ name: 'Tomada de Preços', description: undefined, active: true, subTypes: [], fileId: 63 },
	{ name: 'Convite', description: undefined, active: true, subTypes: [], fileId: 64 },
	{ name: 'Concorrência de Engenharia', description: undefined, active: true, subTypes: [], fileId: 65 },
	{
		name: 'Estudo Técnico Preliminar',
		fileId: 66,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{ name: 'Adesão ao Sistema de Preços', description: undefined, active: true, subTypes: [], fileId: 67 },
	{ name: 'Adiantamentos Contratuais', description: undefined, active: true, subTypes: [], fileId: 68 },
	{ name: 'Compras', description: undefined, active: true, subTypes: [], fileId: 69 },
	{ name: 'Serviços', description: undefined, active: true, subTypes: [], fileId: 70 },
	{ name: 'Engenharia', description: undefined, active: true, subTypes: [], fileId: 71 },
	{ name: 'Serviço de Tecnologia - TIC', description: undefined, active: true, subTypes: [], fileId: 72 },
	{ name: 'Contratação Direta', description: undefined, active: true, subTypes: [], fileId: 73 },
	{
		name: 'Pregão Eletrônico Geral',
		fileId: 74,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{ name: 'Verificação de Obras', description: undefined, active: true, subTypes: [], fileId: 75 },
	{ name: 'Minuta Contratual', description: undefined, active: true, subTypes: [], fileId: 76 },
	{ name: 'Edital de Obras', description: undefined, active: true, subTypes: [], fileId: 77 },
	{ name: 'Projeto Básico', description: undefined, active: true, subTypes: [], fileId: 78 },
	{ name: 'Lista de Verificação', description: undefined, active: true, subTypes: [], fileId: 79 },
	{ name: 'Prorrogação Contratual', description: undefined, active: true, subTypes: [], fileId: 80 },
	{ name: 'Alteração Quantitativa', description: undefined, active: true, subTypes: [], fileId: 81 },
	{ name: 'Compras', description: undefined, active: true, subTypes: [], fileId: 82 },
	{ name: 'Engenharia', description: undefined, active: true, subTypes: [], fileId: 83 },
	{ name: 'Serviços Continuados Exclusivos', description: undefined, active: true, subTypes: [], fileId: 84 },
	{ name: 'Serviços Continuados Não Exclusivos', description: undefined, active: true, subTypes: [], fileId: 85 },
	{ name: 'Serviços Não Continuados', description: undefined, active: true, subTypes: [], fileId: 86 },
	{ name: 'Básica', description: undefined, active: true, subTypes: [], fileId: 87 },
	{ name: 'Condolências', description: undefined, active: true, subTypes: [], fileId: 88 },
	{ name: 'Congratulações', description: undefined, active: true, subTypes: [], fileId: 89 },
	{ name: 'Indicação', description: undefined, active: true, subTypes: [], fileId: 90 },
	{
		name: 'Ofício',
		fileId: 91,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{
		name: 'Questão de Ordem',
		fileId: 92,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{
		name: 'Pareceres',
		fileId: 93,
		description: undefined,
		active: true,
		subTypes: [],
	},
	{ name: 'Contra Declaração de Prejudicialidade', description: undefined, active: true, subTypes: [], fileId: 94 },
	{ name: 'Contra Devolução de Proposição', description: undefined, active: true, subTypes: [], fileId: 95 },
	{ name: 'Contra Presidente Questão de Ordem', description: undefined, active: true, subTypes: [], fileId: 96 },
	{ name: 'Contra Recusa de Emenda Pelo Presidente', description: undefined, active: true, subTypes: [], fileId: 97 },
	{ name: 'Efeito Suspensivo', description: undefined, active: true, subTypes: [], fileId: 98 },
	{ name: 'Contra Parecer de Comissão', description: undefined, active: true, subTypes: [], fileId: 99 },
	{ name: 'Informação', description: undefined, active: true, subTypes: [], fileId: 100 },
	{ name: 'Composição de CPI', description: undefined, active: true, subTypes: [], fileId: 101 },
	{ name: 'De Representação', description: undefined, active: true, subTypes: [], fileId: 102 },
	{ name: 'De Acompanhamento', description: undefined, active: true, subTypes: [], fileId: 103 },
	{ name: 'Comissão Especial(1)', description: undefined, active: true, subTypes: [], fileId: 104 },
	{ name: 'Comissão Especial(2)', description: undefined, active: true, subTypes: [], fileId: 105 },
	{ name: 'Autoridade(1)', description: undefined, active: true, subTypes: [], fileId: 106 },
	{ name: 'Autoridade(2)', description: undefined, active: true, subTypes: [], fileId: 107 },
	{ name: 'Secretário à Plenário', description: undefined, active: true, subTypes: [], fileId: 108 },
	{ name: 'Secretário à Comissão(1)', description: undefined, active: true, subTypes: [], fileId: 109 },
	{ name: 'Secretário à Comissão(2)', description: undefined, active: true, subTypes: [], fileId: 110 },
	{ name: 'Do Cargo', description: undefined, active: true, subTypes: [], fileId: 111 },
	{ name: 'Licença(1)', description: undefined, active: true, subTypes: [], fileId: 112 },
	{ name: 'licença(2)', description: undefined, active: true, subTypes: [], fileId: 113 },
	{ name: 'Missão Cultural', description: undefined, active: true, subTypes: [], fileId: 114 },
	{ name: 'Pesar(1)', description: undefined, active: true, subTypes: [], fileId: 115 },
	{ name: 'Pesar(2)', description: undefined, active: true, subTypes: [], fileId: 116 },
	{ name: 'Sessão Solene', description: undefined, active: true, subTypes: [], fileId: 117 },
	{ name: 'Inclusão de Proposição', description: undefined, active: true, subTypes: [], fileId: 118 },
	{ name: 'Adiamento de Discussão(1)', description: undefined, active: true, subTypes: [], fileId: 119 },
	{ name: 'Adiamento de Discussão(2)', description: undefined, active: true, subTypes: [], fileId: 120 },
	{ name: 'Apreciação em Determinado Dia', description: undefined, active: true, subTypes: [], fileId: 121 },
	{ name: 'Sessão Extraordinária', description: undefined, active: true, subTypes: [], fileId: 122 },
	{ name: 'Inclusão na Odem do Dia', description: undefined, active: true, subTypes: [], fileId: 123 },
	{ name: 'inversão de Pauta', description: undefined, active: true, subTypes: [], fileId: 124 },
	{ name: 'Realização de Diligência', description: undefined, active: true, subTypes: [], fileId: 125 },
	{ name: 'Distribuição de Proposição', description: undefined, active: true, subTypes: [], fileId: 126 },
	{ name: 'Exame de outra Comissão', description: undefined, active: true, subTypes: [], fileId: 127 },
	{ name: 'Prorrogação de Prazo(1)', description: undefined, active: true, subTypes: [], fileId: 128 },
	{ name: 'Prorrogação de Prazo(2)', description: undefined, active: true, subTypes: [], fileId: 129 },
	{ name: 'Tramitação Conjunta(1)', description: undefined, active: true, subTypes: [], fileId: 130 },
	{ name: 'Tramitação Conjunta(2)', description: undefined, active: true, subTypes: [], fileId: 131 },
	{ name: 'Desapensação de Proposição', description: undefined, active: true, subTypes: [], fileId: 132 },
	{ name: 'Desarquivamento', description: undefined, active: true, subTypes: [], fileId: 133 },
	{ name: 'Extinção de Urgência', description: undefined, active: true, subTypes: [], fileId: 134 },
	{ name: 'Juntada de Documentos', description: undefined, active: true, subTypes: [], fileId: 135 },
	{ name: 'Pedido de Vista', description: undefined, active: true, subTypes: [], fileId: 136 },
	{ name: 'Retirada de Proposição', description: undefined, active: true, subTypes: [], fileId: 137 },
	{ name: 'Sobrestamento de Estudo', description: undefined, active: true, subTypes: [], fileId: 138 },
	{ name: 'Rito especial', description: undefined, active: true, subTypes: [], fileId: 139 },
	{ name: 'Urgência', description: undefined, active: true, subTypes: [], fileId: 140 },
	{ name: 'Aplausos', description: undefined, active: true, subTypes: [], fileId: 141 },
	{ name: 'Censura', description: undefined, active: true, subTypes: [], fileId: 142 },
	{ name: 'Destaque', description: undefined, active: true, subTypes: [], fileId: 143 },
	{ name: 'Globo', description: undefined, active: true, subTypes: [], fileId: 144 },
	{ name: 'Em Separado(1)', description: undefined, active: true, subTypes: [], fileId: 145 },
	{ name: 'Em Separado(2)', description: undefined, active: true, subTypes: [], fileId: 146 },
	{ name: 'Nominal', description: undefined, active: true, subTypes: [], fileId: 147 },
	{ name: 'Audiência Pública', description: undefined, active: true, subTypes: [], fileId: 148 },
	{ name: 'Adiantamento de Formalidade', description: undefined, active: true, subTypes: [], fileId: 149 },
	{ name: 'Prorrogação de Posse', description: undefined, active: true, subTypes: [], fileId: 150 },
	{ name: 'Suspensão de Reunião', description: undefined, active: true, subTypes: [], fileId: 151 },
];

export async function up(knex: Knex): Promise<void> {
	return data.forEach(async i => {
		const fromDB = await knex('types').where('name', i.name).first();

		if (fromDB?.id) {
			return knex('types')
				.where('id', fromDB?.id)
				.update(convertDataValues(new PropositionsType({ ...convertDataValues(fromDB, 'camel'), ...i })));
		}
	});
}

export async function down(knex: Knex): Promise<void> {
	return data.forEach(async i => {
		const fromDB = await knex('types').where('name', i.name).first();

		if (fromDB?.id) {
			return knex('types')
				.where('id', fromDB?.id)
				.update({ ...fromDB, file_id: null });
		}
	});
}
